import type { Metadata } from "next";
import Footer from "@/components/ui/footer";
import Header from "@/components/ui/header";

import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Seoul Moment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scroll-smooth" lang="en">
      <body>
        <Header />
        <main className="relative min-h-[calc(100vh-70px)]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
